In [198]:
import torch
import numpy as np
import timeit
from scipy.special import expit as sigmoid

from numba import jit

In [2]:
vec_1 = torch.rand((1000, 10000), device = 'cpu')
vec_2 = torch.rand((10000, 1000), device = 'cpu')

In [3]:
%%timeit
torch.matmul(vec_1, vec_2)

11.1 ms ± 710 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
torch.rand(2,5)*2 - 1

tensor([[ 0.8742, -0.7665, -0.6618,  0.9304, -0.5960],
        [-0.6149,  0.2832,  0.4390,  0.2634, -0.4398]])

In [209]:
vec = torch.rand(100, 100, device = 'cpu')*4 - 2
vec


tensor([[ 0.3857,  1.7113, -0.3298,  ..., -0.0837,  0.1567, -1.5736],
        [-0.2135,  0.6036,  1.5356,  ...,  0.0556,  0.7206, -0.4857],
        [ 0.4483, -1.5239,  0.9814,  ...,  1.0291,  0.5709, -1.3522],
        ...,
        [-0.8994, -1.3244, -0.6786,  ..., -1.9692,  1.2105, -1.8093],
        [ 0.0388, -0.7842, -1.7497,  ..., -0.4083,  1.0703, -0.2278],
        [-1.5943,  1.8713,  1.3633,  ...,  0.4237, -1.3795, -1.2761]])

In [194]:
def tensor_sigmoid(v):
    tens = torch.clone(v)
    if tens.get_device() != -1: tens = tens.to("cpu")
    tens = tens.apply_(sigmoid)
    tens = tens.to('mps')

    return tens

In [195]:
%%timeit
tensor_sigmoid(vec)

3.46 ms ± 12.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [210]:
def tran(tsr):
    return tsr.T



In [215]:
a = torch.clone(tran(vec), device = 'mps')
a

TypeError: clone() got an unexpected keyword argument 'device'

In [213]:
a += 5
a

tensor([[5.3857, 4.7865, 5.4483,  ..., 4.1006, 5.0388, 3.4057],
        [6.7113, 5.6036, 3.4761,  ..., 3.6756, 4.2158, 6.8713],
        [4.6702, 6.5356, 5.9814,  ..., 4.3214, 3.2503, 6.3633],
        ...,
        [4.9163, 5.0556, 6.0291,  ..., 3.0308, 4.5917, 5.4237],
        [5.1567, 5.7206, 5.5709,  ..., 6.2105, 6.0703, 3.6205],
        [3.4264, 4.5143, 3.6478,  ..., 3.1907, 4.7722, 3.7239]])

In [214]:
vec

tensor([[ 0.3857,  1.7113, -0.3298,  ..., -0.0837,  0.1567, -1.5736],
        [-0.2135,  0.6036,  1.5356,  ...,  0.0556,  0.7206, -0.4857],
        [ 0.4483, -1.5239,  0.9814,  ...,  1.0291,  0.5709, -1.3522],
        ...,
        [-0.8994, -1.3244, -0.6786,  ..., -1.9692,  1.2105, -1.8093],
        [ 0.0388, -0.7842, -1.7497,  ..., -0.4083,  1.0703, -0.2278],
        [-1.5943,  1.8713,  1.3633,  ...,  0.4237, -1.3795, -1.2761]])

In [218]:
torch.linspace(0, 1, 5)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [220]:
len(torch.zeros(6,4))

6

In [221]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [249]:
vec_1 = torch.arange(5)**2
vec_2 = torch.arange(5)
vec_3 = vec_1 - (5*vec_2)
vec_3 = vec_3 + vec_1


In [250]:
print(vec_1, vec_2, vec_3, sep= "\n")

tensor([ 0,  1,  4,  9, 16])
tensor([0, 1, 2, 3, 4])
tensor([ 0, -3, -2,  3, 12])


In [251]:
np.array([[s[0]*s[1], s[0] + s[1]] for s in x])

NameError: name 'x' is not defined

In [253]:
torch.stack([torch.arange(5), torch.arange(5)])

tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])